version: '3'

networks:
  web_comp_network:
    driver: bridge
services:
  back-end:
          container_name: ari-backtend
          env_file:
                - ./env/dev.env
          environment:
                - NODE_ENV=dev
          ports:
                  - "7003:1704"
          build: .
          deploy:
                  resources:
                          limits:
                                  cpus: 0.5
                                  memory: 256M

          networks:
                  - web_comp_network
          
