version: '3'

networks:
  web_comp_network:
    driver: bridge
services:
  back-end:
          container_name: ari-backtend
          build: .
          env_file:
                  - /env/prod.env
          ports:
                  - "${SERVER_PORT}:${APP_PORT}"
          deploy:
                  resources:
                          limits:
                                  cpus: 0.5
                                  memory: 256M

          networks:
                  - web_comp_network
          
