version: '3'

networks:
  web_comp_network:
    driver: bridge
services:
  back-end:
          container_name: ari-backtend
          build: .
          ports:
                  - "7003:${SERVER_PORT}"
          deploy:
                  resources:
                          limits:
                                  cpus: 0.5
                                  memory: 256M

          networks:
                  - web_comp_network
          
