version: '3'

networks:
  web_comp_network:
    driver: bridge
services:
  back-end:
          container_name: ari-web-container
          env_file:
                - ./env/prod.env
          environment:
                - NODE_ENV=prod
          ports:
                  - "7003:8888"
          build: .
        #   deploy:
        #           resources:
        #                   limits:
        #                           cpus: 0.5
        #                           memory: 256M

          networks:
                  - web_comp_network
          
