export enum SiteType {
  UNKNOWN = 'UNKNOWN',
  HOME = 'HOME',
  ABOUT_US = 'ABOUT_US',
  ABOUT_TECH = 'ABOUT_TECH',
  RND = 'RND',
  WEB_MOB = 'WEB_MOB',
  OUR_SOURCE = 'OUR_SOURCE',
  DEV_ARI = 'DEV_ARI',
  PARTNER_DOXA = 'PARTNER_DOXA',
  PARTNER_ANS = 'PARTNER_ANS',
  PARTNER = 'PARTNER',
}
